site_name: SQLAlchemy-OrderingItem
docs_dir: docs_md
site_dir: docs
repo_url: https://github.com/dsbowen/sqlalchemy-orderingitem
edit_uri: edit/master/docs_md
nav:
  - Home: index.md
  - Use: use.md
theme: readthedocs
extra_css:
  - css/extra.css